### ISSUE TITLE
Peer review - Live Demo

### ISSUE THREAD

**Issue by veerleprins** [SharonV33/web-app-from-scratch-2021#7]
### Live Demo
- When I click through the demo everything seems to work as I thought, except for one point:
Namely that you can click this way from the detail page to return to the overview page. Maybe you are still planning this but this is not yet visible on the live demo. 
- As an improvement, I would indeed make a 'close' button that takes the user back to the overview page.

**Comment by SharonV33** [comment]
done, thanks
